// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmBA6ZMDd6fIfQAQLN_fc1OXwRu_DHBY',
    appId: '1:1074525941696:web:fe2f690360968a0bb02225',
    messagingSenderId: '1074525941696',
    projectId: 'triptop2024',
    authDomain: 'triptop2024.firebaseapp.com',
    storageBucket: 'triptop2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP71sFkZGF_JTCwcA6j3C2LhUf2w_UJOU',
    appId: '1:1074525941696:android:de46ca1b4e94ddbfb02225',
    messagingSenderId: '1074525941696',
    projectId: 'triptop2024',
    storageBucket: 'triptop2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvN0yTD4sKuwRyTtLy9tJPnPUE_HWNDcA',
    appId: '1:1074525941696:ios:e2756121bc81b315b02225',
    messagingSenderId: '1074525941696',
    projectId: 'triptop2024',
    storageBucket: 'triptop2024.firebasestorage.app',
    iosBundleId: 'com.example.tourisme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvN0yTD4sKuwRyTtLy9tJPnPUE_HWNDcA',
    appId: '1:1074525941696:ios:e2756121bc81b315b02225',
    messagingSenderId: '1074525941696',
    projectId: 'triptop2024',
    storageBucket: 'triptop2024.firebasestorage.app',
    iosBundleId: 'com.example.tourisme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABmBA6ZMDd6fIfQAQLN_fc1OXwRu_DHBY',
    appId: '1:1074525941696:web:b38569950ba66544b02225',
    messagingSenderId: '1074525941696',
    projectId: 'triptop2024',
    authDomain: 'triptop2024.firebaseapp.com',
    storageBucket: 'triptop2024.firebasestorage.app',
  );
}
